EXCEPTION IN (test.py, LINE 38 'uplaod = uplaod_obj.upload_to_IA()'):  error uploading VA_19340704_0004.xml to VA_19340704, b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>500 Internal Server Error</title>\n</head><body>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error or\nmisconfiguration and was unable to complete\nyour request.</p>\n<p>Please contact the server administrator at \n info@archive.org to inform them of the time this error occurred,\n and the actions you performed just before this error.</p>\n<p>More information about this error may be available\nin the server error log.</p>\n<hr>\n<address>Apache/2.4.18 (Ubuntu) Server at s3.us.archive.org Port 80</address>\n</body></html>\n'
EXCEPTION IN (test.py, LINE 30 'metadata_obj = metadata(path)'): file could not be opened successfully
EXCEPTION IN (test.py, LINE 30 'metadata_obj = metadata(path)'): file could not be opened successfully
EXCEPTION IN (test.py, LINE 30 'metadata_obj = metadata(path)'): name 'PrintException' is not defined
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/test.py, LINE 30 'metadata_obj = metadata(path)'): name 'metadata' is not defined
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wb1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 33 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 13 'make_process_folder(path)'): name 'os' is not defined
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wb1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x17/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x17/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ws1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxt/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x4x/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0s/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x8j/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wnm/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9g/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wks/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x2p/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x3v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w51/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x4v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w2r/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wvd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzs/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3m/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wkd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8t/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wwx/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrk/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w4f/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wjw/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrq/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w34/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxf/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wkq/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wbj/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wt8/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x19/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w59/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wqf/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9t/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wz2/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww6/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w95/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 174 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 174 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 52 'self.out.add(obj, arcname=file)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 174 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 33 'self.tf = tarfile.open("%s/1.tar" %(self.jp2))'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 41 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 174 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 42 'for member in self.tf.getmembers():'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 174 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 61 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 71 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 95 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 42 'for member in self.tf.getmembers():'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 174 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 46 'self.tf.extract(member, path='%s/extracted_images/' %(self.processing_folder))'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 63 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 74 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 98 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ws1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 63 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 74 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 98 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 63 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 74 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 98 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0s/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 63 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 74 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 98 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 63 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 74 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 98 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w95/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 177 ''): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 64 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 64 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0s/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 64 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 64 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w95/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 178 'r = upload(self.item_id, files=file_upload, metadata=self.metadata)'): 
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0s/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w95/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wv8/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8z/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0n/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x7k/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wn5/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmc/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3w/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x2k/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w4h/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wpc/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmt/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w82/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6whn/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w71/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wqd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x8b/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wkv/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wm6/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wbs/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x1h/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0b/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wws/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x01/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wm5/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w6v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmk/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wz8/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wgg/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9n/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzg/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3p/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmz/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x41/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x3k/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x1c/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w79/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wsn/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wc2/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wm7/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w4p/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x54/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wf1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wjt/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x2v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6x/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wvb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w97/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wn6/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x2d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wgk/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8j/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w99/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxz/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x1n/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmx/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxn/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wk8/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrj/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wk0/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x7h/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wm4/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wn7/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x15/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww7/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w5z/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6t/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w4d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmn/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x71/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrv/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww2/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wb5/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wc1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8h/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0f/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x21/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxg/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wvj/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww9/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wsc/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x2x/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmh/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x7z/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x79/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w2q/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wx7/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmw/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wnn/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w2p/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wr7/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wtr/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wt6/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3q/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x85/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8n/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w7z/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wkt/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wz3/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wzr/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w54/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wwz/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ws3/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x0w/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wjk/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x5q/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wbn/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w39/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6g/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wr3/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wgx/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wtc/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x80/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w7k/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wn9/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wn4/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wtf/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x08/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x3w/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wsd/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wg1/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x3z/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x26/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wz4/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wc3/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wbw/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w94/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w4r/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wbr/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 43 'for member in self.tf.getmembers():'): unexpected end of data
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w36/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wvk/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wwq/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wj9/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w4v/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wvr/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w3d/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wkb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6whk/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x6q/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w31/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wwg/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wb9/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wwv/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w8b/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxp/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wjj/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x02/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9p/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x2r/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wv3/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x20/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x3s/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w46/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wj4/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9z/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6x5m/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww4/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wxb/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wj7/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wrf/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wtv/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wj3/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wmf/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w2t/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ww0/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w9j/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6ws8/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6wwp/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w44/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w50/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w87/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w85/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 62 'self.alt = tarfile.open("%s/1.tar" %(self.alto))'): file could not be opened successfully
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 75 'for member in self.alt.getmembers():'): 'metadata' object has no attribute 'alt'
EXCEPTION IN (/hdd/projects/metadata/Peel_to_IA/Processing.py, LINE 99 'for mods in os.listdir('%s' %(self.processing_mets)):'): [Errno 2] No such file or directory: 'Vulcan/dig6w86/processing/extracted_mets'
EXCEPTION IN (test.py, LINE 17 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 14 'metadata_obj = metadata(path)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (test.py, LINE 14 'metadata_obj = metadata(path)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (test.py, LINE 14 'metadata_obj = metadata(path)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (test.py, LINE 14 'metadata_obj = metadata(path)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (test.py, LINE 14 'metadata_obj = metadata(path)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 98 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 98 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 98 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 98 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 98 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s/%s' %(self.processing_mods, get_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66f5d50a40>': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66f5d50a40>"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s/%s' %(self.processing_mods, get_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66ffabc150>': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66ffabc150>"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s/%s' %(self.processing_mods, get_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66f5d50a40>': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66f5d50a40>"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s/%s' %(self.processing_mods, get_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66ffabc150>': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66ffabc150>"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s/%s' %(self.processing_mods, get_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66f5d50a40>': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA/<lxml.etree.XSLT object at 0x7f66f5d50a40>"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/peel/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/peel/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/peel/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/peel/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/peel/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/peel/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/peel/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/peel/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 101 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'home/danydvd/git/remote/peel/metadata/Q/VCA.xml': failed to load external entity "home/danydvd/git/remote/peel/metadata/Q/VCA.xml"
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 102 'transformed_mods = get_mets(mod)'): name 'get_mets' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 102 'transformed_mods = get_mets(mod)'): name 'get_mets' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 102 'transformed_mods = get_mets(mod)'): name 'get_mets' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 102 'transformed_mods = get_mets(mod)'): name 'get_mets' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 102 'transformed_mods = get_mets(mod)'): name 'get_mets' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 103 'mods_fields = str(transformed).split('\t')'): name 'transformed' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 103 'mods_fields = str(transformed).split('\t')'): name 'transformed' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 103 'mods_fields = str(transformed).split('\t')'): name 'transformed' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 103 'mods_fields = str(transformed).split('\t')'): name 'transformed' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 103 'mods_fields = str(transformed).split('\t')'): name 'transformed' is not defined
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (test.py, LINE 18 'metadata_process = metadata_obj.get_mets_data(top_mods)'): get_mets_data() takes 1 positional argument but 2 were given
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 154 'item_id = mods.split('.')[0].replace('_article', '')'): 'list' object has no attribute 'split'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 154 'item_id = mods.split('.')[0].replace('_article', '')'): 'list' object has no attribute 'split'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 154 'item_id = mods.split('.')[0].replace('_article', '')'): 'list' object has no attribute 'split'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 154 'item_id = mods.split('.')[0].replace('_article', '')'): 'list' object has no attribute 'split'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 154 'item_id = mods.split('.')[0].replace('_article', '')'): 'list' object has no attribute 'split'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item)'): __init__() missing 1 required positional argument: 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 36 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 45 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 14 'self.code = code'): name 'code' is not defined
EXCEPTION IN (test.py, LINE 15 'metadata_obj = metadata(path, code)'): 'metadata' object has no attribute 'issues'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 14 'self.code = code'): name 'code' is not defined
EXCEPTION IN (test.py, LINE 15 'metadata_obj = metadata(path, code)'): 'metadata' object has no attribute 'issues'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 14 'self.code = code'): name 'code' is not defined
EXCEPTION IN (test.py, LINE 15 'metadata_obj = metadata(path, code)'): 'metadata' object has no attribute 'issues'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 14 'self.code = code'): name 'code' is not defined
EXCEPTION IN (test.py, LINE 15 'metadata_obj = metadata(path, code)'): 'metadata' object has no attribute 'issues'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 14 'self.code = code'): name 'code' is not defined
EXCEPTION IN (test.py, LINE 15 'metadata_obj = metadata(path, code)'): 'metadata' object has no attribute 'issues'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 20 'self.processing_mods = '/home/danydvd/git/remote/peel/metadata/Q/%s.xml' %(self.code)'): 'metadata' object has no attribute 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 99 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 110 'mets_fields = ET.parse(self.get_feilds_xsl)'): 'metadata' object has no attribute 'get_feilds_xsl'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 20 'self.processing_mods = '/home/danydvd/git/remote/peel/metadata/Q/%s.xml' %(self.code)'): 'metadata' object has no attribute 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 99 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 110 'mets_fields = ET.parse(self.get_feilds_xsl)'): 'metadata' object has no attribute 'get_feilds_xsl'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 20 'self.processing_mods = '/home/danydvd/git/remote/peel/metadata/Q/%s.xml' %(self.code)'): 'metadata' object has no attribute 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 99 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 110 'mets_fields = ET.parse(self.get_feilds_xsl)'): 'metadata' object has no attribute 'get_feilds_xsl'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 20 'self.processing_mods = '/home/danydvd/git/remote/peel/metadata/Q/%s.xml' %(self.code)'): 'metadata' object has no attribute 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 99 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 110 'mets_fields = ET.parse(self.get_feilds_xsl)'): 'metadata' object has no attribute 'get_feilds_xsl'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 20 'self.processing_mods = '/home/danydvd/git/remote/peel/metadata/Q/%s.xml' %(self.code)'): 'metadata' object has no attribute 'code'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 99 'mods = ET.parse(self.get_mods_xsl)'): 'metadata' object has no attribute 'get_mods_xsl'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 110 'mets_fields = ET.parse(self.get_feilds_xsl)'): 'metadata' object has no attribute 'get_feilds_xsl'
EXCEPTION IN (test.py, LINE 20 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 34 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 43 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 34 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 43 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 34 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 43 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 34 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 43 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 34 'super().__init__(item, code)'): name 'code' is not defined
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 43 'print ("Extracting %s images" %(self.item_id))'): 'images' object has no attribute 'item_id'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 147 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 173 'values['notes'] = '''): name 'values' is not defined
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 173 'values['notes'] = '''): name 'values' is not defined
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 173 'values['notes'] = '''): name 'values' is not defined
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 108 'print (transformed_mods.getroot().text)'): 'NoneType' object has no attribute 'text'
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 148 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 105 'mod = ET.parse('%s' %(self.processing_mods))'): Namespace prefix mods on mods is not defined, line 2, column 255 (VCA.xml, line 2)
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 105 'mod = ET.parse('%s' %(self.processing_mods))'): Namespace prefix mods on mods is not defined, line 2, column 205 (VCA.xml, line 2)
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): list index out of range
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 158 'values['creator'] = creator'): name 'values' is not defined
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 174 'values['notes'] = '''): name 'values' is not defined
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 105 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'Q/VCA.xml': failed to load external entity "Q/VCA.xml"
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 105 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'Q/VCA.xml': failed to load external entity "Q/VCA.xml"
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 105 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'Q/VCA.xml': failed to load external entity "Q/VCA.xml"
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 105 'mod = ET.parse('%s' %(self.processing_mods))'): Error reading file 'Q/VCA.xml': failed to load external entity "Q/VCA.xml"
EXCEPTION IN (/home/danydvd/git/remote/metadata/scripts/ia/Peel_to_IA/Processing.py, LINE 149 'if len(mods[1]) > 1:'): 'NoneType' object is not subscriptable
EXCEPTION IN (test.py, LINE 19 'item_id = metadata_process[0]'): 'NoneType' object is not subscriptable
